(async function(){
  try {
    console.log(' Index called');

  } catch (err) {
    console.error('Erreur détectée :', err);
  }
})();